name: mobile_bootcamp_template
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  dio: ^5.9.0
  retrofit: ^4.9.2
  json_annotation: ^4.9.0
  get_it: ^9.2.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  google_fonts: ^8.0.0
  build_runner: ^2.10.5
  flutter_localizations:
    sdk: flutter
  envied: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  retrofit_generator: ^10.2.1
  json_serializable: ^6.11.2
  spider: ^4.2.3
  envied_generator: ^1.3.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
